language: node_js

node_js:
    - node

notifications:
    email:
        recipients:
            - srz222@gmail.com
        on_success: always
        on_failure: always

# safelist
branches:
  only:
  - master
  